### ISSUE TITLE
caps-cli push 

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/ModelCatalogInsertion#10]
In the readme it states running `caps-cli push <path_to_yaml>` will generate a `transformed_json.json` in the root directory (im assuming of the program). However when I ran 
`caps-cli push examples/ModelConfigExample.yaml` 
from within the program's root dir it would print out a json to the terminal but no `transformed_json.json` would be created.

I also tried to cd into the examples directory and ran the command again but this produced the same result. 

I also recommend giving log outputs to let the user know what the program is doing. For example telling them things like: 
- "INFO: Converting ModelConfigEample.yaml into JSON"
- "ERROR: Could not find C:/Users/Admin/ModelCatalogInsertion/test.yaml"
- "INFO: Generated transformed_json.json"
- "Success"

This will be especially helpful to new users of the program.

**Comment by dhruvp-8** [comment]
@Cmheidelberg. My mistake while writing the READMe.md this behavior is seen on initialize command. For now the push command is only printing data to stdout

I agree with the logging thing!

**Comment by Cmheidelberg** [comment]
@dhruvp-8 I was just about to leave a comment about that because I took a peek at the code :P

On another note: Although fine in the short run I don't know how practical leaving the json on the user's computer is since it is only being created to talk to the Model Cat. We can talk about this at tomorrows meeting since this point is more just future planning anyway.

**Comment by dhruvp-8** [comment]
@Cmheidelberg the entire pipeline for push command is still in progress so we decided to make it stdout for now.

**Comment by maurya-rohit** [comment]
Just to add onto that, the basic aim of this to directly push the json to the model catalog. Since that part is still under development and integration is remaining. So we thought writing it to file or stdout would be good for just to demonstrate what is the current output.

**Comment by dgarijo** [comment]
The logging issue part has not been solved, right? If so, please open a new issue with that (or reopen this one)
