### ISSUE TITLE
I wouldn't recommend writing all the code in __main__.py 

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/ModelCatalogInsertion#11]
I've noticed that a lot of the code for each function has been written in the __main__.py file. I would recommend making a new python file for each command and writing all the code in there. This will really help with readability and scalability as the program grows larger. [wcm](https://github.com/mintproject/wcm/tree/master/src/wcm) is a good reference point for this.

**Comment by maurya-rohit** [comment]
I think this is a good idea. Thanks!!
