### ISSUE TITLE
Initialized YAML should have comments to guide a developer

### ISSUE THREAD

**Issue by dgarijo** [mintproject/ModelCatalogInsertion#17]
The YAML should say what goes into the fileds (input 1, input 2, etc.).

**Comment by Cmheidelberg** [comment]
This should be resolved now see my pr: https://github.com/mintproject/ModelCatalogInsertion/pull/20

**Comment by dgarijo** [comment]
Minor things pending:
`name: # Multiple names supported`
It's not multiple names, it's multiple contributors.
`hasComponentLocation: # URL to component executable`
should be to "executable component"
```
hasModelCategory: # Optional
   - # String category
```
In String category, say: e.g., Hydrology
In `hasOutputTimeInterval: # Optional`
there are 2 properties that are very important: the intervalUnit (e.g., day) and the intervalValue (e.g., 1)

In the second input in the comment it says: "Name of first var". It should be "second". Or just say: Input of var 2

In parameter, it says:
`value: # Optional value`
The comment should say: "If the parameter has fixed value in this setup, add it here"

**Comment by Cmheidelberg** [comment]
Almost forgot. This has been addressed in my commit last Saturday.

**Comment by dgarijo** [comment]
All right, closing
