### ISSUE TITLE
Command line interface should initialize

### ISSUE THREAD

**Issue by dgarijo** [mintproject/ModelCatalogInsertion#5]
The command line should allow something like:
mic (for model-inserction-cli) initialize -i 3 -o 4 -p 10 and generate the template yaml with 3 inputs, 4 outputs and 10 parameters.

**Comment by dgarijo** [comment]
The CLI should initialize the YAML file, not the JSON

**Comment by dgarijo** [comment]
The CLI creates a YAML file, but it's not a human-friendly YAML as described in the examples

**Comment by dgarijo** [comment]
Also, remember that the YAML should be the simplified version I gave in the examples

**Comment by Cmheidelberg** [comment]
This should be resolved now. See my pr for details: https://github.com/mintproject/ModelCatalogInsertion/pull/20
