### ISSUE TITLE
Make CLI pip-installable

### ISSUE THREAD

**Issue by dgarijo** [mintproject/ModelCatalogInsertion#6]
So we can use it easily

**Comment by dgarijo** [comment]
Move to review when the package is in pypi

**Comment by mosoriob** [comment]
Travis has been setup. 
When you release a new version on Github, Travis is going to upload a new version on PyPI.

You can use https://github.com/release-it/release-it

WARNING: You must modify the version on the __init__.py
```
$ cat src/caps/__init__.py                                                                    ✔ | 19s 
__version__ = "0.1.1"
```
