### ISSUE TITLE
Help gets cut off

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/ModelCatalogInsertion#9]
**Problem:**
The `caps-cli --help` returns cut off descriptions for `initialization` and `push` commands.
```bash
Admin@DESKTOP-K03KE3P MINGW64 ~/Desktop/USC/Internships/ISI/ModelCatalogInsertion (caps-cli)
$ caps-cli --help
Usage: caps-cli [OPTIONS] COMMAND [ARGS]...

Options:
  -v, --verbose
  --help         Show this message and exit.

Commands:
  initialize  Create an empty JSON template to fill the data to be inserted...
  push        Transform the input YAML into a Valid JSON for posting the...
  validate    Validate the JSON obtained after creating one
  version     Show caps-cli version.
```
 

**FIX:**
I think you can use `short_help=""` in the `@cli.command()` to give a short overview description of the command so it doesnt get cut off. Then the `help=""` will show the full help message when the user gets help on the specific command.

**Comment by dhruvp-8** [comment]
Thanks for the input @Cmheidelberg. I will fix it.

**Comment by dgarijo** [comment]
@Cmheidelberg, for small fixes you can also clone and do pull request :)
